version: 0
allowPullRequests: public
metadata:
  name: "Mozilla RelEng"
  description: "Mozilla RelEng Services"
  owner: "{{ event.head.user.email }}"
  source: "{{ event.head.repo.url }}"
tasks:

  - metadata:
      name: "setup"
      description: ""
      owner: "{{ event.head.user.email }}"
      source: "https://github.com/mozilla-releng/services/tree/taskcluster-rework"
    extra:
      github:
        env: true
        events:
          - pull_request.*
          - push
        branches:
          - taskcluster-rework
    provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      maxRunTime: 7200  # seconds (i.e. two hours)
      image: "nixos/nix:latest"
      features:
        taskclusterProxy: true
      env:
        TASKCLUSTER_SECRETS: "taskcluster/secrets/v1/secret/repo:github.com/mozilla-releng/services:branch:staging"
      command:
        - "/bin/bash"
        - "-c"
        - "nix-env -iA nixpkgs.curl && mkdir /app && cd /app && curl -L https://github.com/mozilla-releng/services/archive/$GITHUB_HEAD_SHA.tar.gz -o $GITHUB_HEAD_SHA.tar.gz && tar zxf $GITHUB_HEAD_SHA.tar.gz && cd services-$GITHUB_HEAD_SHA && nix-shell nix/taskcluster.nix --pure --argstr taskcluster_secrets $TASKCLUSTER_SECRETS"
